### ISSUE TITLE
Issue with data quality 

### ISSUE THREAD

**Issue by wjs20** [sarahsirin/AB-Bind-Database#1]
Hi

I have been attempting to use some data from your database for modelling but it seems like there is an issue with some of the data values. Many of the data values for the integrin-mab affinity dataset take on a dd G value of 8, while no datapoints appear to take on this value in the original paper. Many of the other measured ddG values appear not to match either. Can you confirm that the experimentally determined values in the .csv file are the correct values for this dataset? 

Thankyou

**Comment by sarahsirin** [comment]
Hi, 
The values reported for ddGs have been checked multiple times. If multiple values were reported, then the values were averaged. All data were converted to ddG where the wild-type was used as the baseline. And units were converted to kcal/mol for consistency.  ddG of 8 kcal/mol were used to annotate non-binder mutations.  Also, please note that for some antibody complexes, there were multiple publications where ddG values were extracted from.  If you have any specific questions about particular value, I'll be happy to confirm for you.
